### ISSUE TITLE
 [error] Ranch listener :poxa had connection process started with :cowboy_protocol:start_link/4

### ISSUE THREAD

**Issue by CatMallV** [edgurgel/poxa#126]
We are sending notifications using pusher/pusher-php-server ver 3.0.4
Sometimes notifications are sent ok but generally we are getting something like this:

```
07:32:45.524 [error] Error in process #PID<0.997.0> on node :"poxa@127.0.0.1" with exit value:
{{:case_clause,
  {false,
   {:http_req, #Port<0.2326>, :ranch_tcp, :keepalive, #PID<0.997.0>, "POST",
    :"HTTP/1.1", {{192, 168, 1, 216}, 52877}, "192.168.1.2", :undefined, 8080,
    "/apps/app_id/events", :undefined,
    "auth_key=app_key&auth_signature=3fa65ae218527fccfcd209891fa0323fbf50edc7a348eccb28cf9da77f6deb45&auth_timestamp=1529479171&auth_version=1.0&body_md5=c452ff4acabe59474ed12f4abe4317f5",
    [{"auth_key", "app_key"},
     {"auth_signature",
      "3fa65ae218527fccfcd209891fa0323fbf50edc7a348eccb28cf9da77f6deb45"},
     {"auth_timestamp", "1529479171"}, {"auth_version", "1.0"},
     {"body_md5", "c452ff4acabe59474ed12f4abe4317f5"}], [app_id: "app_id"],
    [{"host", "192.168.1.2:8080"}, {"accept", "*/*"},
     {"content-type", "application/json"},
     {"x-pusher-library", "pusher-http-php 3.0.0"}, {"content-length", "109"}],
    [{"content-length", 109}, {"expect", :undefined}], :undefined, [], :done,
    "", :undefined, false, :waiting, [], "{\"error\":\"Authentication error\"}",
    :undefined},
   %{body: "{\"name\":\"test_event\",\"data\":\"{\\\"event\\\":\\\"test_event\\\",\\\"data\\\":\\\"test_data\\\"}\",\"channels\":[\"test_channnel\"]}",
     event: %Poxa.PusherEvent{channels: ["test_channnel"],
      data: "{\"event\":\"test_event\",\"data\":\"test_data\"}",
      name: "test_event", socket_id: nil}}}},
 [{:cowboy_rest, :is_authorized, 2,
   [file: '/source/deps/cowboy/src/cowboy_rest.erl', line: 150]},
  {:cowboy_protocol, :execute, 4,
   [file: '/source/deps/cowboy/src/cowboy_protocol.erl', line: 442]}]}


07:32:45.528 [error] Ranch listener :poxa had connection process started with :cowboy_protocol:start_link/4 at #PID<0.997.0> exit with reason: {{:case_clause, {false, {:http_req, #Port<0.2326>, :ranch_tcp, :keepalive, #PID<0.997.0>, "POST", :"HTTP/1.1", {{192, 168, 1, 216}, 52877}, "192.168.1.2", :undefined, 8080, "/apps/app_id/events", :undefined, "auth_key=app_key&auth_signature=3fa65ae218527fccfcd209891fa0323fbf50edc7a348eccb28cf9da77f6deb45&auth_timestamp=1529479171&auth_version=1.0&body_md5=c452ff4acabe59474ed12f4abe4317f5", [{"auth_key", "app_key"}, {"auth_signature", "3fa65ae218527fccfcd209891fa0323fbf50edc7a348eccb28cf9da77f6deb45"}, {"auth_timestamp", "1529479171"}, {"auth_version", "1.0"}, {"body_md5", "c452ff4acabe59474ed12f4abe4317f5"}], [app_id: "app_id"], [{"host", "192.168.1.2:8080"}, {"accept", "*/*"}, {"content-type", "application/json"}, {"x-pusher-library", "pusher-http-php 3.0.0"}, {"content-length", "109"}], [{"content-length", 109}, {"expect", :undefined}], :undefined, [], :done, "", :undefined, false, :waiting, [], "{\"error\":\"Authentication error\"}", :undefined}, %{body: "{\"name\":\"test_event\",\"data\":\"{\\\"event\\\":\\\"test_event\\\",\\\"data\\\":\\\"test_data\\\"}\",\"channels\":[\"test_channnel\"]}", event: %Poxa.PusherEvent{channels: ["test_channnel"], data: "{\"event\":\"test_event\",\"data\":\"test_data\"}", name: "test_event", socket_id: nil}}}}, [{:cowboy_rest, :is_authorized, 2, [file: '/source/deps/cowboy/src/cowboy_rest.erl', line: 150]}, {:cowboy_protocol, :execute, 4, [file: '/source/deps/cowboy/src/cowboy_protocol.erl', line: 442]}]}



```

**Comment by edgurgel** [comment]
Hey thanks! I'm not very proficient with PHP but could you help me find an easy way to replicate this issue? 🤔

**Comment by Dian8** [comment]
I have same issue. To reproduce:
  
  Use docker image edgurgel/poxa-automated:latest
  
  Install "pusher/pusher-php-server": "^3.0.4" via composer
  
  Code for sending message is like:

	$pusher =
		new Pusher\Pusher(
			'app_key',
			'app_secret',
			'app_id',
			[
				'host' => 127.0.0.1,
				'port' => 8080,
			]
		);

	$pusher->trigger('channel_id', 'event_id', ['data']);

Sometimes it works properly. But sometimes results this issue.

**Comment by edgurgel** [comment]
cool thanks for extra details, @Dian8

**Comment by edgurgel** [comment]
So it was basically saying that the authentication is wrong. Can you check if you are using the correct secret, app_key, etc?

It could be also that the php client is not signing the request properly 🤔 

Now you should get `401 unauthorized ` once this is merged and released.

**Comment by Dian8** [comment]
Tested: this issue is now gone. Thanks!

**Comment by edgurgel** [comment]
Awesome! Thanks for the feedback!

**Comment by vetal20600** [comment]
@edgurgel got same issue. I don't have any php at all
`01:39:26.896 [error] Ranch listener :poxa had connection process started with :cowboy_protocol:start_link/4 at #PID<0.4868.0> exit with reason: {[reason: {:badmatch, {:error, :enoent}}, mfa: {:cowboy_static, :rest_init, 2}, stacktrace: [{:filename, :absname, 1, [file: 'filename.erl', line: 73]}, {:cowboy_static, :rest_init_opts, 2, [file: '/home/m5ultiacuser_/poxa_/deps/cowboy/src/cowboy_static.erl', line: 64]}, {:cowboy_rest, :upgrade, 4, [file: '/home/m5ultiacuser_/poxa_/deps/cowboy/src/cowboy_rest.erl', line: 64]}, {:cowboy_protocol, :execute, 4, [file: '/home/m5ultiacuser_/poxa_/deps/cowboy/src/cowboy_protocol.erl', line: 442]}], req: [socket: #Port<0.6050>, transport: :ranch_tcp, connection: :keepalive, pid: #PID<0.4868.0>, method: "GET", version: :"HTTP/1.1", peer: {{109, 227, 126, 215}, 51749}, host: "pusheralternative.cf", host_info: :undefined, port: 80, path: "/", path_info: :undefined, qs: "", qs_vals: :undefined, bindings: [], headers: [{"host", "pusheralternative.cf"}, {"connection", "keep-alive"}, {"cache-control", "max-age=0"}, {"upgrade-insecure-requests", "1"}, {"user-agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36 OPR/54.0.2952.54"}, {"accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8"}, {"accept-encoding", "gzip, deflate"}, {"accept-language", "en-US,en;q=0.9"}, {"if-none-match", "W/\"5b5242eb-264\""}, {"if-modified-since", "Fri, 20 Jul 2018 20:15:39 GMT"}], p_headers: [{"connection", ["keep-alive"]}], cookies: :undefined, meta: [], body_state: :waiting, buffer: "", multipart: :undefined, resp_compress: false, resp_state: :waiting, resp_headers: [], resp_body: "", onresponse: :undefined], opts: {:priv_file, :poxa, 'index.html'}], [{:cowboy_rest, :upgrade, 4, [file: '/home/m5ultiacuser_/poxa_/deps/cowboy/src/cowboy_rest.erl', line: 71]}, {:cowboy_protocol, :execute, 4, [file: '/home/m5ultiacuser_/poxa_/deps/cowboy/src/cowboy_protocol.erl', line: 442]}]}`
