### ISSUE TITLE
Scalability

### ISSUE THREAD

**Issue by N4COM** [edgurgel/poxa#161]
I'm looking for a pusher replacement or a server with private channel supports and broadcasting. Poxa seems be fine but I'm wondering if it is scalable horizontally. Can it work with several poxa nodes and a load balancer?

**Comment by edgurgel** [comment]
Hi @N4COM,

Not possible today. There were discussions about this before but never a PR to introduce such thing. Options were: using Distributed Erlang with gproc or using Redis to connect nodes and gproc locally.

**Comment by N4COM** [comment]
OK, thanks for your reply.

**Comment by Hengjie** [comment]
@edgurgel how would you setup Redis to connect nodes and gproc locally? Would you be write up a tutorial on it? Thanks!

**Comment by tibbon** [comment]
How's the vertical scaling of it? Debating how big of a system we can run with this...

**Comment by jcs224** [comment]
I'm curious about this as well. There's nothing really like this in the OSS as far as I can find, except for maybe Socket.io. Elixir seems better suited for this problem, however. The easiest way today would probably be using Redis with PubSub to emit events to a bunch of connected nodes. New to Elixir but could be fun to play with. Pusher is just too expensive if you have a lot of connections.

**Comment by arrowcircle** [comment]
@jcs224  there is OSS https://github.com/centrifugal/centrifugo but not compatible with pusher.

**Comment by jcs224** [comment]
Thanks @arrowcircle, this looks quite neat! The Pusher compatibility would be my choice, because it would integrate with the Pusher client code already used in a lot of places. The Forem project is also looking at this tool, wanted to use their existing Pusher code but make it full OSS and scalable.

https://forem.dev/ben/explore-poxa-as-an-open-pusher-implementation-14dd
